# Generated by Django 4.2.7 on 2023-11-21 07:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataInput',
            fields=[
                ('input_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usia', models.CharField(max_length=255)),
                ('jenis_makanan', models.EmailField(choices=[('sehat', 'Sehat'), ('cepaatsaji', 'Cepat Saji')], max_length=254)),
                ('alergi_makanan', models.CharField(choices=[('tidak', 'Tidak'), ('iya', 'Iya')], max_length=255)),
                ('melewatkan_sarapan', models.CharField(choices=[('iya', 'Iya'), ('tidak', 'Tidak')], max_length=255)),
                ('makan_sehari', models.CharField(max_length=255)),
                ('makan_teratur', models.CharField(choices=[('iya', 'Iya'), ('tidak', 'Tidak')], max_length=255)),
                ('tingkat_penting_pilih_makanan', models.CharField(choices=[('sangatpenting', 'Sangat Penting'), ('penting', 'Penting'), ('kurangpenting', 'Kurang Penting'), ('tidakpenting', 'Tidak Penting')], max_length=255)),
                ('olahraga_seminggu', models.CharField(max_length=255)),
            ],
        ),
    ]
