# Generated by Django 4.2.7 on 2023-11-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gayahidup', '0002_alter_datainput_jenis_makanan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datainput',
            options={'verbose_name': 'DataInput', 'verbose_name_plural': 'DataInputs'},
        ),
    ]
